//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Auth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Auth() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoList.Localization.Auth", typeof(Auth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDoList.
        /// </summary>
        public static string AuthLayout_Brand {
            get {
                return ResourceManager.GetString("AuthLayout_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string AuthLayout_Nav_Label {
            get {
                return ResourceManager.GetString("AuthLayout_Nav_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login_Button_Submit {
            get {
                return ResourceManager.GetString("Login_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите, чтобы управлять своими задачами..
        /// </summary>
        public static string Login_Header_Lead {
            get {
                return ResourceManager.GetString("Login_Header_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login_Header_Title {
            get {
                return ResourceManager.GetString("Login_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login_Label_Login {
            get {
                return ResourceManager.GetString("Login_Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Login_Label_Password {
            get {
                return ResourceManager.GetString("Login_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login_Page_Title {
            get {
                return ResourceManager.GetString("Login_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш логин.
        /// </summary>
        public static string Login_Placeholder_Login {
            get {
                return ResourceManager.GetString("Login_Placeholder_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Login_Placeholder_Password {
            get {
                return ResourceManager.GetString("Login_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Login_Switch_Link {
            get {
                return ResourceManager.GetString("Login_Switch_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта?.
        /// </summary>
        public static string Login_Switch_Text {
            get {
                return ResourceManager.GetString("Login_Switch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения..
        /// </summary>
        public static string Login_Validation_Required {
            get {
                return ResourceManager.GetString("Login_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать аккаунт.
        /// </summary>
        public static string Registration_Button_Submit {
            get {
                return ResourceManager.GetString("Registration_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создайте аккаунт — задачи будут доступны только вам..
        /// </summary>
        public static string Registration_Header_Lead {
            get {
                return ResourceManager.GetString("Registration_Header_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration_Header_Title {
            get {
                return ResourceManager.GetString("Registration_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string Registration_Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Registration_Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration_Page_Title {
            get {
                return ResourceManager.GetString("Registration_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string Registration_Placeholder_ConfirmPassword {
            get {
                return ResourceManager.GetString("Registration_Placeholder_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Придумайте логин.
        /// </summary>
        public static string Registration_Placeholder_Login {
            get {
                return ResourceManager.GetString("Registration_Placeholder_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Придумайте пароль.
        /// </summary>
        public static string Registration_Placeholder_Password {
            get {
                return ResourceManager.GetString("Registration_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Registration_Switch_Link {
            get {
                return ResourceManager.GetString("Registration_Switch_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть аккаунт?.
        /// </summary>
        public static string Registration_Switch_Text {
            get {
                return ResourceManager.GetString("Registration_Switch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот логин уже занят.
        /// </summary>
        public static string Validation_LoginTaken {
            get {
                return ResourceManager.GetString("Validation_LoginTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну цифру..
        /// </summary>
        public static string Validation_PasswordMustContainDigit {
            get {
                return ResourceManager.GetString("Validation_PasswordMustContainDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен начинаться с заглавной буквы..
        /// </summary>
        public static string Validation_PasswordMustStartUpper {
            get {
                return ResourceManager.GetString("Validation_PasswordMustStartUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать..
        /// </summary>
        public static string Validation_PasswordsMustMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль слишком короткий..
        /// </summary>
        public static string Validation_PasswordTooShort {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort", resourceCulture);
            }
        }
    }
}
