//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoList.Localization.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Р’СЃРµ Р°РєС‚РёРІРЅС‹Рµ.
        /// </summary>
        public static string Dashboard_Action_AllActive {
            get {
                return ResourceManager.GetString("Dashboard_Action_AllActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + РќРѕРІР°СЏ Р·Р°РґР°С‡Р°.
        /// </summary>
        public static string Dashboard_Action_NewTask {
            get {
                return ResourceManager.GetString("Dashboard_Action_NewTask", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р‘С‹СЃС‚СЂС‹Рµ РґРµР№СЃС‚РІРёСЏ.
        /// </summary>
        public static string Dashboard_Actions_Title {
            get {
                return ResourceManager.GetString("Dashboard_Actions_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РљР°Р»РµРЅРґР°СЂСЊ Р·Р°РґР°С‡.
        /// </summary>
        public static string Dashboard_Calendar_Label {
            get {
                return ResourceManager.GetString("Dashboard_Calendar_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎР»РµРґСѓСЋС‰РёР№ РјРµСЃСЏС†.
        /// </summary>
        public static string Dashboard_Calendar_Next {
            get {
                return ResourceManager.GetString("Dashboard_Calendar_Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџСЂРµРґС‹РґСѓС‰РёР№ РјРµСЃСЏС†.
        /// </summary>
        public static string Dashboard_Calendar_Prev {
            get {
                return ResourceManager.GetString("Dashboard_Calendar_Prev", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РљР°Р»РµРЅРґР°СЂСЊ.
        /// </summary>
        public static string Dashboard_Calendar_Title {
            get {
                return ResourceManager.GetString("Dashboard_Calendar_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} РёР· {1} Р·Р°РґР°С‡ РІС‹РїРѕР»РЅРµРЅРѕ.
        /// </summary>
        public static string Dashboard_Progress_Hint {
            get {
                return ResourceManager.GetString("Dashboard_Progress_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџСЂРѕРіСЂРµСЃСЃ.
        /// </summary>
        public static string Dashboard_Progress_Title {
            get {
                return ResourceManager.GetString("Dashboard_Progress_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РђРєС‚РёРІРЅС‹Рµ.
        /// </summary>
        public static string Dashboard_Stat_Active {
            get {
                return ResourceManager.GetString("Dashboard_Stat_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р“РѕС‚РѕРІРѕ.
        /// </summary>
        public static string Dashboard_Stat_Done {
            get {
                return ResourceManager.GetString("Dashboard_Stat_Done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџСЂРѕСЃСЂРѕС‡РµРЅРѕ.
        /// </summary>
        public static string Dashboard_Stat_Failed {
            get {
                return ResourceManager.GetString("Dashboard_Stat_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РќРµС‚ Р·Р°РґР°С‡ СЃ РґРµРґР»Р°Р№РЅРѕРј.
        /// </summary>
        public static string Dashboard_Upcoming_Empty {
            get {
                return ResourceManager.GetString("Dashboard_Upcoming_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р‘Р»РёР¶Р°Р№С€РёРµ СЃСЂРѕРєРё.
        /// </summary>
        public static string Dashboard_Upcoming_Title {
            get {
                return ResourceManager.GetString("Dashboard_Upcoming_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџС‚.
        /// </summary>
        public static string Dashboard_Weekday_Fri {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Fri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџРЅ.
        /// </summary>
        public static string Dashboard_Weekday_Mon {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Mon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎР±.
        /// </summary>
        public static string Dashboard_Weekday_Sat {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Sat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’СЃ.
        /// </summary>
        public static string Dashboard_Weekday_Sun {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Sun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р§С‚.
        /// </summary>
        public static string Dashboard_Weekday_Thu {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Thu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’С‚.
        /// </summary>
        public static string Dashboard_Weekday_Tue {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Tue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎСЂ.
        /// </summary>
        public static string Dashboard_Weekday_Wed {
            get {
                return ResourceManager.GetString("Dashboard_Weekday_Wed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎРѕР·РґР°С‚СЊ Р·Р°РґР°С‡Сѓ.
        /// </summary>
        public static string DoneList_Empty_Link {
            get {
                return ResourceManager.GetString("DoneList_Empty_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’С‹РїРѕР»РЅРµРЅРЅС‹С… Р·Р°РґР°С‡ РїРѕРєР° РЅРµС‚..
        /// </summary>
        public static string DoneList_Empty_Message {
            get {
                return ResourceManager.GetString("DoneList_Empty_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р”РµР»Р°, РєРѕС‚РѕСЂС‹Рµ СѓР¶Рµ Р·Р°РІРµСЂС€РµРЅС‹.
        /// </summary>
        public static string DoneList_Header_Lead {
            get {
                return ResourceManager.GetString("DoneList_Header_Lead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’С‹РїРѕР»РЅРµРЅРЅС‹Рµ Р·Р°РґР°С‡Рё.
        /// </summary>
        public static string DoneList_Header_Title {
            get {
                return ResourceManager.GetString("DoneList_Header_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’С‹РїРѕР»РЅРµРЅРЅС‹Рµ Р·Р°РґР°С‡Рё.
        /// </summary>
        public static string DoneList_Page_Title {
            get {
                return ResourceManager.GetString("DoneList_Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎРѕР·РґР°С‚СЊ Р·Р°РґР°С‡Сѓ.
        /// </summary>
        public static string FailedList_Empty_Link {
            get {
                return ResourceManager.GetString("FailedList_Empty_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџСЂРѕРІР°Р»РµРЅРЅС‹С… Р·Р°РґР°С‡ РїРѕРєР° РЅРµС‚..
        /// </summary>
        public static string FailedList_Empty_Message {
            get {
                return ResourceManager.GetString("FailedList_Empty_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р”РµР»Р°, РєРѕС‚РѕСЂС‹Рµ РЅРµ СѓРґР°Р»РѕСЃСЊ Р·Р°РІРµСЂС€РёС‚СЊ РІ СЃСЂРѕРє.
        /// </summary>
        public static string FailedList_Header_Lead {
            get {
                return ResourceManager.GetString("FailedList_Header_Lead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџСЂРѕРІР°Р»РµРЅРЅС‹Рµ Р·Р°РґР°С‡Рё.
        /// </summary>
        public static string FailedList_Header_Title {
            get {
                return ResourceManager.GetString("FailedList_Header_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РџСЂРѕРІР°Р»РµРЅРЅС‹Рµ Р·Р°РґР°С‡Рё.
        /// </summary>
        public static string FailedList_Page_Title {
            get {
                return ResourceManager.GetString("FailedList_Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎРѕР·РґР°С‚СЊ Р·Р°РґР°С‡Сѓ.
        /// </summary>
        public static string Index_Button_Create {
            get {
                return ResourceManager.GetString("Index_Button_Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РћС‡РёСЃС‚РёС‚СЊ.
        /// </summary>
        public static string Index_Button_Reset {
            get {
                return ResourceManager.GetString("Index_Button_Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р—РґРѕСЂРѕРІСЊРµ.
        /// </summary>
        public static string Index_Category_Health {
            get {
                return ResourceManager.GetString("Index_Category_Health", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р”РѕРј.
        /// </summary>
        public static string Index_Category_Home {
            get {
                return ResourceManager.GetString("Index_Category_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЈС‡С‘Р±Р°.
        /// </summary>
        public static string Index_Category_Study {
            get {
                return ResourceManager.GetString("Index_Category_Study", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р Р°Р±РѕС‚Р°.
        /// </summary>
        public static string Index_Category_Work {
            get {
                return ResourceManager.GetString("Index_Category_Work", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РќРѕРІР°СЏ Р·Р°РґР°С‡Р°.
        /// </summary>
        public static string Index_Header_Create_Card {
            get {
                return ResourceManager.GetString("Index_Header_Create_Card", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р—Р°РїРѕР»РЅРёС‚Рµ РїРѕР»СЏ. Р”Р°С‚Сѓ РјРѕР¶РЅРѕ РІС‹Р±СЂР°С‚СЊ РІ РєР°Р»РµРЅРґР°СЂРµ СЃР»РµРІР°..
        /// </summary>
        public static string Index_Header_Create_Card_Lead {
            get {
                return ResourceManager.GetString("Index_Header_Create_Card_Lead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РљР°С‚РµРіРѕСЂРёСЏ.
        /// </summary>
        public static string Index_Label_Category {
            get {
                return ResourceManager.GetString("Index_Label_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎСЂРѕРє.
        /// </summary>
        public static string Index_Label_DeadlineDate {
            get {
                return ResourceManager.GetString("Index_Label_DeadlineDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’СЂРµРјСЏ.
        /// </summary>
        public static string Index_Label_DeadlineTime {
            get {
                return ResourceManager.GetString("Index_Label_DeadlineTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РћРїРёСЃР°РЅРёРµ.
        /// </summary>
        public static string Index_Label_Description {
            get {
                return ResourceManager.GetString("Index_Label_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’Р°Р¶РЅР°СЏ Р·Р°РґР°С‡Р°.
        /// </summary>
        public static string Index_Label_Important {
            get {
                return ResourceManager.GetString("Index_Label_Important", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РќР°Р·РІР°РЅРёРµ.
        /// </summary>
        public static string Index_Label_Name {
            get {
                return ResourceManager.GetString("Index_Label_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’Р°Р¶РЅРѕСЃС‚СЊ.
        /// </summary>
        public static string Index_Label_Priority {
            get {
                return ResourceManager.GetString("Index_Label_Priority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎС‚Р°С‚СѓСЃ.
        /// </summary>
        public static string Index_Label_Status {
            get {
                return ResourceManager.GetString("Index_Label_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РњРµС‚РєР°.
        /// </summary>
        public static string Index_Label_Tag {
            get {
                return ResourceManager.GetString("Index_Label_Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РќРѕРІР°СЏ Р·Р°РґР°С‡Р°.
        /// </summary>
        public static string Index_Page_Title {
            get {
                return ResourceManager.GetString("Index_Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р Р°Р±РѕС‚Р°, РґРѕРјвЂ¦.
        /// </summary>
        public static string Index_Placeholder_Category {
            get {
                return ResourceManager.GetString("Index_Placeholder_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р”РµС‚Р°Р»Рё, СЃСЃС‹Р»РєРё, Р·Р°РјРµС‚РєРёвЂ¦.
        /// </summary>
        public static string Index_Placeholder_Description {
            get {
                return ResourceManager.GetString("Index_Placeholder_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РќР°РїСЂРёРјРµСЂ: РџРѕРґРіРѕС‚РѕРІРёС‚СЊ РѕС‚С‡С‘С‚.
        /// </summary>
        public static string Index_Placeholder_Name {
            get {
                return ResourceManager.GetString("Index_Placeholder_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎСЂРѕС‡РЅР°СЏ.
        /// </summary>
        public static string Index_Priority_High {
            get {
                return ResourceManager.GetString("Index_Priority_High", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р›С‘РіРєР°СЏ.
        /// </summary>
        public static string Index_Priority_Low {
            get {
                return ResourceManager.GetString("Index_Priority_Low", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎСЂРµРґРЅСЏСЏ.
        /// </summary>
        public static string Index_Priority_Medium {
            get {
                return ResourceManager.GetString("Index_Priority_Medium", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’С‹РїРѕР»РЅРµРЅР°.
        /// </summary>
        public static string Index_Status_Done {
            get {
                return ResourceManager.GetString("Index_Status_Done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РђРєС‚РёРІРЅР°СЏ.
        /// </summary>
        public static string Index_Status_InProgress {
            get {
                return ResourceManager.GetString("Index_Status_InProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РќР°Р·РІР°РЅРёРµ РѕР±СЏР·Р°С‚РµР»СЊРЅРѕ РґР»СЏ Р·Р°РїРѕР»РЅРµРЅРёСЏ..
        /// </summary>
        public static string Index_Validation_Name_Required {
            get {
                return ResourceManager.GetString("Index_Validation_Name_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’Р°Р¶РЅР°СЏ.
        /// </summary>
        public static string ToDoList_Badge_Important {
            get {
                return ResourceManager.GetString("ToDoList_Badge_Important", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎРѕР·РґР°С‚СЊ РїРµСЂРІСѓСЋ.
        /// </summary>
        public static string ToDoList_Empty_Link {
            get {
                return ResourceManager.GetString("ToDoList_Empty_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р—Р°РґР°С‡ РїРѕРєР° РЅРµС‚..
        /// </summary>
        public static string ToDoList_Empty_Message {
            get {
                return ResourceManager.GetString("ToDoList_Empty_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎРїРёСЃРѕРє РґРµР», СЃРѕР·РґР°РЅРЅС‹С… РЅР° СЃС‚СЂР°РЅРёС†Рµ В«РќРѕРІР°СЏ Р·Р°РґР°С‡Р°В».
        /// </summary>
        public static string ToDoList_Header_Lead {
            get {
                return ResourceManager.GetString("ToDoList_Header_Lead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’СЃРµ Р·Р°РґР°С‡Рё.
        /// </summary>
        public static string ToDoList_Header_Title {
            get {
                return ResourceManager.GetString("ToDoList_Header_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РљР°С‚РµРіРѕСЂРёСЏ.
        /// </summary>
        public static string ToDoList_Meta_Category {
            get {
                return ResourceManager.GetString("ToDoList_Meta_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎСЂРѕРє.
        /// </summary>
        public static string ToDoList_Meta_Deadline {
            get {
                return ResourceManager.GetString("ToDoList_Meta_Deadline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’Р°Р¶РЅРѕСЃС‚СЊ.
        /// </summary>
        public static string ToDoList_Meta_Priority {
            get {
                return ResourceManager.GetString("ToDoList_Meta_Priority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to РЎС‚Р°С‚СѓСЃ.
        /// </summary>
        public static string ToDoList_Meta_Status {
            get {
                return ResourceManager.GetString("ToDoList_Meta_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Р’СЃРµ Р·Р°РґР°С‡Рё.
        /// </summary>
        public static string ToDoList_Page_Title {
            get {
                return ResourceManager.GetString("ToDoList_Page_Title", resourceCulture);
            }
        }
    }
}