//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoList.Localization.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цветовая схема задач.
        /// </summary>
        public static string ColorLegend_Label {
            get {
                return ResourceManager.GetString("ColorLegend_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочена.
        /// </summary>
        public static string ColorLegend_Overdue {
            get {
                return ResourceManager.GetString("ColorLegend_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета.
        /// </summary>
        public static string ColorLegend_Title {
            get {
                return ResourceManager.GetString("ColorLegend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2026 — ToDoList.
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апрель.
        /// </summary>
        public static string Js_Month_Apr {
            get {
                return ResourceManager.GetString("Js_Month_Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        public static string Js_Month_Aug {
            get {
                return ResourceManager.GetString("Js_Month_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декабрь.
        /// </summary>
        public static string Js_Month_Dec {
            get {
                return ResourceManager.GetString("Js_Month_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февраль.
        /// </summary>
        public static string Js_Month_Feb {
            get {
                return ResourceManager.GetString("Js_Month_Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Январь.
        /// </summary>
        public static string Js_Month_Jan {
            get {
                return ResourceManager.GetString("Js_Month_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июль.
        /// </summary>
        public static string Js_Month_Jul {
            get {
                return ResourceManager.GetString("Js_Month_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июнь.
        /// </summary>
        public static string Js_Month_Jun {
            get {
                return ResourceManager.GetString("Js_Month_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string Js_Month_Mar {
            get {
                return ResourceManager.GetString("Js_Month_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string Js_Month_May {
            get {
                return ResourceManager.GetString("Js_Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноябрь.
        /// </summary>
        public static string Js_Month_Nov {
            get {
                return ResourceManager.GetString("Js_Month_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октябрь.
        /// </summary>
        public static string Js_Month_Oct {
            get {
                return ResourceManager.GetString("Js_Month_Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сентябрь.
        /// </summary>
        public static string Js_Month_Sep {
            get {
                return ResourceManager.GetString("Js_Month_Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to активна.
        /// </summary>
        public static string Js_Status_Active {
            get {
                return ResourceManager.GetString("Js_Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выполнена.
        /// </summary>
        public static string Js_Status_Done {
            get {
                return ResourceManager.GetString("Js_Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просрочена.
        /// </summary>
        public static string Js_Status_Failed {
            get {
                return ResourceManager.GetString("Js_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} задач(и).
        /// </summary>
        public static string Js_TasksCount {
            get {
                return ResourceManager.GetString("Js_TasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи на {0}.
        /// </summary>
        public static string Js_TasksOn {
            get {
                return ResourceManager.GetString("Js_TasksOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Lang_Label {
            get {
                return ResourceManager.GetString("Lang_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RU.
        /// </summary>
        public static string Lang_Russian {
            get {
                return ResourceManager.GetString("Lang_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все задачи.
        /// </summary>
        public static string Nav_AllTasks {
            get {
                return ResourceManager.GetString("Nav_AllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполненные.
        /// </summary>
        public static string Nav_Done {
            get {
                return ResourceManager.GetString("Nav_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проваленные.
        /// </summary>
        public static string Nav_Failed {
            get {
                return ResourceManager.GetString("Nav_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Nav_LogIn {
            get {
                return ResourceManager.GetString("Nav_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Nav_LogOut {
            get {
                return ResourceManager.GetString("Nav_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая задача.
        /// </summary>
        public static string Nav_NewTask {
            get {
                return ResourceManager.GetString("Nav_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Nav_Registration {
            get {
                return ResourceManager.GetString("Nav_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть меню.
        /// </summary>
        public static string Nav_ToggleMenu {
            get {
                return ResourceManager.GetString("Nav_ToggleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срочная.
        /// </summary>
        public static string Priority_High {
            get {
                return ResourceManager.GetString("Priority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лёгкая.
        /// </summary>
        public static string Priority_Low {
            get {
                return ResourceManager.GetString("Priority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя.
        /// </summary>
        public static string Priority_Medium {
            get {
                return ResourceManager.GetString("Priority_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель управления.
        /// </summary>
        public static string Sidebar_Label {
            get {
                return ResourceManager.GetString("Sidebar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активна.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнена.
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провалена.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить выполненной задачу {0}.
        /// </summary>
        public static string Task_Complete_AriaLabel {
            get {
                return ResourceManager.GetString("Task_Complete_AriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить выполненной.
        /// </summary>
        public static string Task_Complete_Title {
            get {
                return ResourceManager.GetString("Task_Complete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить задачу {0}.
        /// </summary>
        public static string Task_Delete_AriaLabel {
            get {
                return ResourceManager.GetString("Task_Delete_AriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить задачу «{0}»?.
        /// </summary>
        public static string Task_Delete_Confirm {
            get {
                return ResourceManager.GetString("Task_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить задачу.
        /// </summary>
        public static string Task_Delete_Title {
            get {
                return ResourceManager.GetString("Task_Delete_Title", resourceCulture);
            }
        }
    }
}
